[tool.poetry]
name = "pkg-testing-01"
version = "0.1.0"
description = ""
authors = ["George Lenton <georgelenton@gmail.com>"]
readme = "README.md"
packages = [{include = "pkg_testing_01"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
