name: Semantic Release

on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        run: |
          npm i -D @semantic-release/commit-analyzer
          npm i -D semantic-release-replace-plugin

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TK_TST_01 }}

