# default commit conventions that are used:
# https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format
name: Semantic Release

on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies and run semantic release
        run: |
          npm i -D @semantic-release/commit-analyzer
          npm i -D @semantic-release/git
          npm i -D semantic-release-replace-plugin
          npx semantic-release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
